# Generated by Django 3.0 on 2022-03-26 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=10, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=10, verbose_name='Имя пользователя')),
                ('male', models.CharField(max_length=10, verbose_name='Пол пользователя')),
                ('email', models.CharField(max_length=10, verbose_name='Email пользователя')),
                ('questuins', models.TextField(verbose_name='Пройденые ответы')),
                ('answers', models.TextField(verbose_name='Ответы пользователя')),
                ('result_bal', models.CharField(max_length=10, verbose_name='Результат для подсчета')),
            ],
            options={
                'verbose_name': 'Результат ответов',
                'verbose_name_plural': 'Результаты ответов',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('legend', models.TextField(verbose_name='Легенда вопроса')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.Quiz')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('tultype', models.TextField(verbose_name='Подсказка к ответу')),
                ('min_bal', models.IntegerField(default=0, verbose_name='Минимальное значение ответа')),
                ('max_bal', models.IntegerField(verbose_name='Максимальное значение ответа')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
            options={
                'verbose_name': 'Ответы',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
