# Generated by Django 3.0 on 2022-03-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='legend',
            field=models.TextField(blank=True, verbose_name='Легенда вопроса'),
        ),
    ]
