# Generated by Django 3.0 on 2022-03-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='value_answer',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
    ]
