# Generated by Django 3.0 on 2022-03-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20220326_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='legend',
            field=models.TextField(blank=True, null=True, verbose_name='Легенда вопроса'),
        ),
    ]
