# Generated by Django 3.0 on 2022-03-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_answer_value_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value_answer',
            field=models.CharField(max_length=200),
        ),
    ]
