# Generated by Django 3.0 on 2022-03-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20220326_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='tultype',
            field=models.TextField(blank=True, null=True, verbose_name='Подсказка к ответу'),
        ),
    ]
