# Generated by Django 3.0 on 2022-03-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_result_answers_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result_answers',
            name='color',
            field=models.CharField(blank=True, default='notcolor', max_length=200, null=True),
        ),
    ]
