# Generated by Django 3.0 on 2022-03-27 10:01

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20220326_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultanswers',
            name='email',
            field=models.CharField(max_length=10, null=True, verbose_name='Email пользователя'),
        ),
        migrations.AlterField(
            model_name='resultanswers',
            name='userID',
            field=models.CharField(default=questions.models.ResultAnswers.random_number, max_length=10, verbose_name='Уникальный идентификатор'),
        ),
    ]
