# Generated by Django 3.0 on 2022-04-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20220331_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='cause',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
