# Generated by Django 3.0 on 2022-03-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20220327_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='male',
            field=models.CharField(blank=True, choices=[('man', 'man'), ('woman', 'woman')], max_length=6, null=True),
        ),
    ]
