# Generated by Django 3.0 on 2022-04-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_answer_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='cause',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
