# Generated by Django 3.0 on 2022-03-27 10:06

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='step',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Позиция в опросе'),
        ),
        migrations.AlterField(
            model_name='question',
            name='male',
            field=models.CharField(blank=True, choices=[('all', 'all'), ('man', 'man'), ('woman', 'woman')], default=builtins.all, max_length=6, null=True),
        ),
    ]
