# Generated by Django 3.0 on 2022-03-27 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20220327_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultanswers',
            name='id',
        ),
        migrations.AlterField(
            model_name='resultanswers',
            name='userID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
