# Generated by Django 3.0 on 2022-04-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20220418_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='result_answers',
            name='cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='cause',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
