# Generated by Django 3.0 on 2022-03-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20220327_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultanswers',
            name='answers',
            field=models.TextField(blank=True, verbose_name='Ответы пользователя'),
        ),
    ]
