# Generated by Django 3.0 on 2022-03-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20220327_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('questions', models.CharField(max_length=500)),
                ('result', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='resultanswers',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Email пользователя'),
        ),
        migrations.AlterField(
            model_name='resultanswers',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя пользователя'),
        ),
    ]
