# Generated by Django 3.0 on 2022-03-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20220327_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='min_bal',
            field=models.IntegerField(verbose_name='Минимальное значение ответа'),
        ),
    ]
