# Generated by Django 3.0 on 2022-03-29 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название блока')),
                ('low', models.CharField(default=0, max_length=120, verbose_name='low')),
                ('medium', models.CharField(default=0, max_length=120, verbose_name='medium')),
                ('hard', models.CharField(default=0, max_length=120, verbose_name='hard')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=120)),
                ('legend', models.TextField(blank=True, null=True, verbose_name='Легенда вопроса')),
                ('gender', models.CharField(choices=[('all', 'all'), ('man', 'man'), ('woman', 'woman')], default='all', max_length=20)),
                ('title_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.BlockQuiz')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
    ]
