# Generated by Django 3.0 on 2022-04-30 02:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название блока')),
                ('low', models.CharField(default=0, editable=False, max_length=120, verbose_name='low')),
                ('medium', models.CharField(default=0, editable=False, max_length=120, verbose_name='medium')),
                ('hard', models.CharField(default=0, editable=False, max_length=120, verbose_name='hard')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='Result_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('questions', models.CharField(max_length=500)),
                ('causes', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=20)),
                ('color', models.CharField(blank=True, default='notcolor', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Результат ответов',
                'verbose_name_plural': 'Результаты ответов',
            },
        ),
        migrations.CreateModel(
            name='ResultAnswers',
            fields=[
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=10, verbose_name='Имя пользователя')),
                ('cause', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(max_length=10, verbose_name='Пол пользователя')),
                ('email', models.CharField(max_length=10, null=True, verbose_name='Email пользователя')),
            ],
            options={
                'verbose_name': 'Учасник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=120)),
                ('legend', models.TextField(blank=True, null=True, verbose_name='Легенда вопроса')),
                ('gender', models.CharField(choices=[('all', 'all'), ('man', 'man'), ('woman', 'woman')], default='all', max_length=20)),
                ('low', models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='low')),
                ('medium', models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='medium')),
                ('hard', models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='hard')),
                ('title_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.BlockQuiz')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('legend', models.TextField(blank=True, null=True, verbose_name='Легенда вопроса')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.Quiz')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('value_answer', models.CharField(max_length=200)),
                ('cause', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.Question')),
            ],
            options={
                'verbose_name': 'Ответы',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
