# Generated by Django 3.0 on 2022-03-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockquiz',
            name='hard',
            field=models.CharField(default=0, editable=False, max_length=120, verbose_name='hard'),
        ),
        migrations.AlterField(
            model_name='blockquiz',
            name='low',
            field=models.CharField(default=0, editable=False, max_length=120, verbose_name='low'),
        ),
        migrations.AlterField(
            model_name='blockquiz',
            name='medium',
            field=models.CharField(default=0, editable=False, max_length=120, verbose_name='medium'),
        ),
    ]
