# Generated by Django 3.0 on 2022-05-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAnsvers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=255, verbose_name='Идентификатор')),
                ('count', models.CharField(max_length=255, verbose_name='Попытка')),
                ('quiz', models.CharField(max_length=255, verbose_name='Опросник')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('ansver_values', models.CharField(max_length=255, verbose_name='Ответ')),
                ('cause', models.CharField(blank=True, max_length=200, null=True, verbose_name='Потологии')),
            ],
            options={
                'verbose_name': 'NEW Результат ответов',
                'verbose_name_plural': 'NEW Результаты ответов',
            },
        ),
    ]
