# Generated by Django 3.0 on 2022-03-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_auto_20220329_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='hard',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='hard'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='low',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='low'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='medium',
            field=models.CharField(blank=True, default=0, max_length=120, null=True, verbose_name='medium'),
        ),
    ]
