# Generated by Django 3.0 on 2022-05-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_newansvers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='count',
            field=models.CharField(default=0, max_length=255, verbose_name='Попытка'),
        ),
    ]
