# Generated by Django 3.0 on 2022-05-16 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_result_answers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newansvers',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.Question'),
        ),
    ]
