# Generated by Django 3.0 on 2022-05-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0007_auto_20220516_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='count',
        ),
    ]
