# Generated by Django 3.0 on 2022-05-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0008_remove_answer_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Cause')),
                ('text_body', models.TextField(verbose_name='Cause text')),
                ('text_cause', models.TextField(verbose_name='Cause or text')),
            ],
            options={
                'verbose_name': 'Cause',
                'verbose_name_plural': 'Causes',
            },
        ),
    ]
