# Generated by Django 3.0 on 2022-04-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Никнейм')),
                ('gender', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пол')),
                ('massa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вес')),
                ('purpose', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цели')),
                ('decision', models.CharField(blank=True, max_length=255, null=True, verbose_name='Решение')),
                ('problem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Проблемы')),
            ],
            options={
                'verbose_name': 'Данные пользователя',
                'verbose_name_plural': 'Данные пользователtq',
            },
        ),
    ]
