# Generated by Django 3.0 on 2022-04-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Никнейм')),
                ('age', models.CharField(blank=True, max_length=255, null=True, verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пол')),
                ('massa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вес')),
                ('purpose', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цели')),
                ('decision', models.CharField(blank=True, max_length=255, null=True, verbose_name='Решение')),
                ('problem', models.BooleanField()),
                ('problem_two', models.BooleanField()),
                ('problem_fre', models.BooleanField()),
                ('problem_foo', models.BooleanField()),
                ('problem_fiv', models.BooleanField()),
                ('problem_sex', models.BooleanField()),
                ('problem_sev', models.BooleanField()),
                ('problem_ech', models.BooleanField()),
                ('problem_noi', models.BooleanField()),
                ('problem_thn', models.BooleanField()),
                ('problem_elv', models.BooleanField()),
                ('problem_lav', models.BooleanField()),
                ('problem_ulw', models.BooleanField()),
                ('problem_flv', models.BooleanField()),
                ('problem_fvt', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Данные пользователя',
                'verbose_name_plural': 'Данные пользователей',
            },
        ),
    ]
