# Generated by Django 3.0 on 2022-05-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20220501_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='count',
            field=models.CharField(default=0, max_length=20, verbose_name='Количество попыток'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Transgender', 'Transgender'), ('Intersex', 'Intersex'), ('I prefer not to say', 'I prefer not to say'), ('Other', 'Other')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem',
            field=models.BooleanField(verbose_name='1'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem_ech',
            field=models.BooleanField(blank=True, null=True, verbose_name='8'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem_elv',
            field=models.BooleanField(blank=True, null=True, verbose_name='11'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem_fiv',
            field=models.BooleanField(blank=True, null=True, verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem_flv',
            field=models.BooleanField(blank=True, null=True, verbose_name='15'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem_foo',
            field=models.BooleanField(blank=True, null=True, verbose_name='4'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem_fre',
            field=models.BooleanField(blank=True, null=True, verbose_name='3'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem_fvt',
            field=models.BooleanField(blank=True, null=True, verbose_name='16'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem_lav',
            field=models.BooleanField(blank=True, null=True, verbose_name='13'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem_noi',
            field=models.BooleanField(blank=True, null=True, verbose_name='9'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem_sev',
            field=models.BooleanField(blank=True, null=True, verbose_name='7'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem_sex',
            field=models.BooleanField(blank=True, null=True, verbose_name='6'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem_thn',
            field=models.BooleanField(blank=True, null=True, verbose_name='10'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem_two',
            field=models.BooleanField(blank=True, null=True, verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem_ulw',
            field=models.BooleanField(blank=True, null=True, verbose_name='14'),
        ),
    ]
