# Generated by Django 3.0 on 2022-05-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20220515_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='count',
            field=models.CharField(default=1, max_length=20, verbose_name='Количество попыток'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='problem',
            field=models.BooleanField(blank=True, null=True, verbose_name='1'),
        ),
    ]
